version: '3'
services:
  phaser_vite:
    build: .
    container_name: phaser-vite
    ports:
      - '9020:9020'
    volumes:
      - .:/home/node/app:rw
    restart: 'no'
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
